services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: contents-hub-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - contents-hub  

    db:
        image: postgres:15
        container_name: contents-hub-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5444:${DB_PORT}"
        volumes:
            - contents-hub:/var/lib/postgresql/data
        networks:
            - contents-hub  

    nginx:
        image: nginx:alpine
        container_name: contents-hub-nginx
        ports:
            - "90:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - contents-hub

volumes:
    contents-hub:

networks:
    contents-hub:
        driver: bridge